### ISSUE TITLE
Pop up: sophie would like to see the trivia displayed clearly on her phone screen in an uncluttered way

### ISSUE THREAD

**Issue by OliviaWinteringham** [SchoolOfCode/final-project-app-brumgo-front-end#21]
Sophie wants to see the trivia about the POI displayed on a Pop up so she sees clearly the information that is relevant to that POI

- [x] when Sophie has navigated close to a POI on the map she can see the icon of the POI displayed
- [x] once Sophie has long pressed on the icon a Pop-up is displayed
- [x] text is displayed on the Pop-up it is relevant to the POI
