### ISSUE TITLE
Sophie, Andrew and Carl want to have a simple user interface but something that is fun. She would like to see page transitions happen with animations, this will retain their interest

### ISSUE THREAD

**Issue by Aardeedev** [SchoolOfCode/final-project-app-brumgo-front-end#29]
- [ ] Implement react navigation v2 or 3 in project
- [ ] setup react navigation to move between views
- [ ] find suitable transition animations and apply to view changes
