### ISSUE TITLE
GEO-FENCING: the user wants the app to track their location and for the POI info to display when they are in close proximity to it

### ISSUE THREAD

**Issue by OliviaWinteringham** [SchoolOfCode/final-project-app-brumgo-front-end#43]
- [x] calculate distance between points - Latitude and Longitude points
- [x] calculate distance between user and all POI in area
- [x] trigger an alert / pop-up when within specified range of POI
- [ ] visual feedback to user of top three closest POIs
