### ISSUE TITLE
SEARCH / FILTER Sophie, Carl and Andrew want to be able to search through the list of POI by type so they can choose where to go

### ISSUE THREAD

**Issue by OliviaWinteringham** [SchoolOfCode/final-project-app-brumgo-front-end#49]
- [x] ensure the list of POIs is available and complete with at least 10 points of interest for the user to visit. This will include bars / places to eat, cultural sites, historical sites
- [x] add working button(s) to the footer to allow the user to press for the search option
- [ ] create a search / filter function for the user to interact with
