### ISSUE TITLE
GAMIFICATION: Carl wants to be able to enage with Digbeth and the local sites in a way that is fun and entertains his family while they learn something new

### ISSUE THREAD

**Issue by OliviaWinteringham** [SchoolOfCode/final-project-app-brumgo-front-end#51]
- [ ] design way in which tokens will be collected by user
- [ ] implement a scoring system so the user can keep track of the number of tokens they collect
- [ ] locate tokens at specific points at POI 
- [ ] implement authentication so the user can have a profile and save their token collection to it
- [ ] AR button (in pop up) needs to open the camera
