### ISSUE TITLE
ROUTES: Sophie and Carl would like to be able to follow a route using brumGo that takes them from a starting point to an ending point and shows them various sites along the way

### ISSUE THREAD

**Issue by OliviaWinteringham** [SchoolOfCode/final-project-app-brumgo-front-end#54]
- [ ] implement a API, i.e. Google directions or similar to allow the user to follow at route around the local area
- [ ] enhance the user experience with animations on the route, such as a guided arrow feature, images, or audio directions
- [ ] explore how to implement an AR character guide to enhance the user experience
