### ISSUE TITLE
users would like to be able to access directions to POI from the list view by clicking on directions button

### ISSUE THREAD

**Issue by OliviaWinteringham** [SchoolOfCode/final-project-app-brumgo-front-end#90]
- [x] research suitable API, google directions
- [x] write relevant logic 
- [ ] use current data in digbethPOI.js to identify destinations
- [ ] link Yellow direction button in footer to logic
- [ ] link directions button in Listview to logic
