### ISSUE TITLE
USER PROFILE: the user would like to be able to register a profile on the app so they can save their favourite POIs

### ISSUE THREAD

**Issue by OliviaWinteringham** [SchoolOfCode/final-project-app-brumgo-front-end#93]
- [x] create a user profile page
- [x] allow users to register a profile with their name, email and password
- [x] allow users to login to the app through the login page
